name = "backend"
compatibility_date = "2023-12-01"

[vars]
MY_VARIABLE = "production_value"
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYTFlNDZkOGYtZTFlOS00YWExLThlNGUtMTlhYmJlNTk4NTEzIiwidGVuYW50X2lkIjoiODliMjU1MWQzZDAyMjQyNzAwNThjYjMwZTg1M2QyYWJhNjQxOWY2MTFiMGJhNzM4YmQ1MDZjZmUxZGI1NzhmNyIsImludGVybmFsX3NlY3JldCI6IjI4NWQ4M2M3LTA1M2EtNDIzNy1iOWZlLTUyYjAxNzBkZDE4ZiJ9.Tw9eG0pSzUTs9Y-eXwpK1PvZX5gBca0E2hCUs-pgZUk"
JWT_SECRET="hitin"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
